plugin:
  infusionsoft_enabled:
    default: true
    client: true
  infusionsoft_client_id:
    default: ''
    client: true
  infusionsoft_client_secret:
    default: ''
  infusionsoft_tag_group_map:
    type: list
    default: ''
  infusionsoft_trading_room_tag_id:
    default: 132
